### ISSUE TITLE
Порядок

### ISSUE THREAD

**Issue by sanasus** [cultserv/stylelint-config-ponominalu#5]
пример: 
{
  $colorBlack: #000;
  color: $colorBlack;

  @extend %test;
  @include test;

  &:before { }

  @include media-lg { }
  @media () { }
}

заменить правило на это 
"order/order": [
        "at-variables",
        "declarations",
        {
          "type": "at-rule",
          "name": "extend"
        },
        {
          "type": "at-rule",
          "name": "include",
          "hasBlock": false
        },
        "rules",
        "at-rules"
      ]

**Comment by qertis** [comment]
готово
